REPORT  Z_TEST1.
DATA input TYPE /iscer/s_amount.
DATA re     TYPE cers_spell.
input-CURRENCYCODE = 'CAD'.
input-AMOUNTVALUE = '300233213134523'.
CALL METHOD CL_CER_CONV_AMOUNT_INTO_WORDS=>SPELL_AMOUNT(
       exporting IS_AMOUNT = input
                 iv_language = sy-langu
       importing es_words = re ).
write / 'ok'.

result:THREE HUNDRED TRILLIONSTWO HUNDRED THIRTY-THREE BILLIONS  TWO HUNDRED THIRTEEN MILLION ONE HUNDRED THIRTY-FOUR THOUSAND FIVE HUNDRED TWENTY-THREE